Repository DevOps-MBSE/aac-puml, pull requests merged in 2024-04, with the labels that each got.

#12 Adding Puml commands work to puml api
  .github/workflows/python-test-python-version.yml
  archive/__init__.py
  archive/gen_puml_impl.py
  archive/generate_plantuml_diagrams_impl.py
  archive/legacy_puml_helpers.py
  python/pyproject.toml
  python/src/puml/__init__.py
  python/src/puml/generate_plantuml_diagrams_impl.py
  python/src/puml/generators/component_diagram_generator.aac
  python/src/puml/generators/object_diagram_generator.aac
  python/src/puml/generators/requirements_diagram_generator.aac
  python/src/puml/generators/sequence_diagram_generator.aac
  python/src/puml/puml_helpers.py
  python/tests/__init__.py
  python/tests/generate_plantuml_diagrams_component_diagram_test.feature
  python/tests/generate_plantuml_diagrams_object_diagram_test.feature
  python/tests/generate_plantuml_diagrams_requirement_diagram_test.feature
  python/tests/generate_plantuml_diagrams_sequence_diagram_test.feature
  python/tests/test_generate_plantuml_diagrams.py
  python/tox.ini
Labels: added

#13 Puml api
  .github/workflows/python-test-python-version.yml
  .github/workflows/sphinx.yml
  .vscode/launch.json
  .vscode/settings.json
  README.md
  docs/notes.txt
  docs/source/alarm_clock/alarm_clock.yaml
  docs/source/alarm_clock/external.yaml
  docs/source/alarm_clock/structures.yaml
  docs/source/alarm_clock/usecase.yaml
  python/MANIFEST.in
  python/README.txt
  python/pyproject.toml
  python/requirements.in
  python/requirements.txt
  python/src/puml/__init__.py
  python/src/puml/aac/plugins/puml/__init__.py
  python/src/puml/aac/plugins/puml/__init__.py.aac_backup
  python/src/puml/aac/plugins/puml/generate_plantuml_diagrams_impl.py
  python/src/puml/aac/plugins/puml/generate_plantuml_diagrams_impl.py.aac_evaluate
  python/src/puml/gen_plant_uml_impl.py
  python/src/puml/generate_plantuml_diagrams.aac
  python/src/puml/generate_plantuml_diagrams_impl.py
  python/src/puml/generators/component_diagram_generator.aac
  python/src/puml/generators/object_diagram_generator.aac
  python/src/puml/generators/requirements_diagram_generator.aac
  python/src/puml/generators/sequence_diagram_generator.aac
  python/src/puml/puml_helpers.py
  python/src/puml/puml_requirements.py
  python/tests/__init__.py
  python/tests/generate_plantuml_diagrams_component_diagram_test.feature
  python/tests/generate_plantuml_diagrams_object_diagram_test.feature
  python/tests/generate_plantuml_diagrams_requirement_diagram_test.feature
  python/tests/generate_plantuml_diagrams_sequence_diagram_test.feature
  python/tests/test_gen_plant_uml.py
  python/tests/test_generate_plantuml_diagrams.py
  python/tox.ini
Labels: added

#14 9 update puml sequence diagram template
  docs/notes.txt
  python/pyproject.toml
  python/src/puml/__init__.py
  python/src/puml/generate_plantuml_diagrams.aac
  python/src/puml/generate_plantuml_diagrams_impl.py
  python/src/puml/generators/sequence_diagram_generator.aac
  python/src/puml/helpers/__init__.py
  python/src/puml/helpers/sequence_helpers.py
  python/src/puml/templates/sequence/sequence_diagram.puml.jinja2
  python/tests/alarm_clock/alarm_clock.yaml
  python/tests/alarm_clock/external.yaml
  python/tests/alarm_clock/structures.yaml
  python/tests/alarm_clock/usecase.yaml
  python/tests/test_generate_plantuml_diagrams.py
Labels: added

#15 Puml component template
  python/pyproject.toml
  python/src/puml/__init__.py
  python/src/puml/generate_plantuml_diagrams_impl.py
  python/src/puml/helpers/component_helpers.py
  python/src/puml/templates/component/component_diagram.puml.jinja2
  python/tests/alarm_clock/alarm_clock.yaml
  python/tests/test_generate_plantuml_diagrams.py
Labels: added

#16 Puml object template
  python/pyproject.toml
  python/src/puml/__init__.py
  python/src/puml/generate_plantuml_diagrams_impl.py
  python/src/puml/helpers/object_helpers.py
  python/src/puml/templates/object/object_diagram.puml.jinja2
  python/tests/test_generate_plantuml_diagrams.py
Labels: added

#17 10 update puml requirements diagram template
  .github/workflows/python-build-and-lint.yml
  .github/workflows/python-cross-platform-support.yml
  .vscode/settings.json
  python/pyproject.toml
  python/src/puml/__init__.py
  python/src/puml/generate_plantuml_diagrams.aac
  python/src/puml/generate_plantuml_diagrams_impl.py
  python/src/puml/generators/requirements_diagram_generator.aac
  python/src/puml/helpers/component_helpers.py
  python/src/puml/helpers/object_helpers.py
  python/src/puml/helpers/requirements_helpers.py
  python/src/puml/helpers/sequence_helpers.py
  python/src/puml/templates/component/component_diagram.puml.jinja2
  python/src/puml/templates/object/object_diagram.puml.jinja2
  python/src/puml/templates/requirements/requirements_diagram.puml.jinja2
  python/src/puml/templates/sequence/sequence_diagram.puml.jinja2
  python/tests/calc/model/MathFunction.yaml
  python/tests/calc/model/MathRequest.yaml
  python/tests/calc/model/MathResponse.yaml
  python/tests/calc/model/calculator.yaml
  python/tests/calc/model/mathlogger.yaml
  python/tests/calc/model/mathmessagehandler.yaml
  python/tests/calc/spec/Add_SRS.yaml
  python/tests/calc/spec/Calculator_IRS.yaml
  python/tests/calc/spec/Calculator_SystemSpec.yaml
  python/tests/calc/spec/ComplexMath_PIDS.yaml
  python/tests/calc/spec/Divide_SRS.yaml
  python/tests/calc/spec/IntermediateMath_PIDS.yaml
  python/tests/calc/spec/Multiply_SRS.yaml
  python/tests/calc/spec/Power_SRS.yaml
  python/tests/calc/spec/SimpleMath_PIDS.yaml
  python/tests/calc/spec/SquareRoot_SRS.yaml
  python/tests/calc/spec/Subtract_SRS.yaml
  python/tests/test_generate_plantuml_component.py
  python/tests/test_generate_plantuml_diagrams.py
  python/tests/test_generate_plantuml_object.py
  python/tests/test_generate_plantuml_requirements.py
  python/tests/test_generate_plantuml_sequence.py
Labels: added

#18 11 update puml documentation
  .github/workflows/python-cross-platform-support.yml
  .github/workflows/python-deploy-artifacts.yml
  .github/workflows/sphinx.yml
  README.md
  docs/source/aac_puml.md
  docs/source/component_examples.md
  docs/source/images/component_files.png
  docs/source/images/object_files.png
  docs/source/images/requirements_files.png
  docs/source/images/sequence_files.png
  docs/source/index.rst
  docs/source/object_examples.md
  docs/source/requirements_examples.md
  docs/source/sequence_examples.md
  docs/source/supported_puml_diagrams.md
  python/pyproject.toml
  python/src/puml/templates/requirements/requirements_diagram.puml.jinja2
Labels: documentation, added

#20 PyPi Deployment
  .github/workflows/python-build-and-lint.yml
  python/pyproject.toml
Labels: changed

#22 Puml PyPi Deployment
  .github/workflows/python-build-and-lint.yml
  .github/workflows/python-deploy-artifacts.yml
  python/pyproject.toml
Labels: changed
